### PR TITLE
Add CODER

### PR DESCRIPTION
**Pull request by DanTup**

### CODE REVIEW

**Comment by kiriakos** [comment]
Hey there! thanks for submitting. There seems to be an error with the json in the PR. the json-schema currently expects all keys, even if their values are just empry strings. Can you re submit please?

**Comment by DanTup** [comment]
Oops sorry, my bad! Should be fixed now. Thanks!

**Comment by DanTup** [comment]
@kiriakos I resolved the conflict (and left my pool above the new ones, to avoid it conflicting with other PRs adding to the end that may be merged before it).

**Review by lophre — DISMISSED** [review]

**Comment by lophre** [comment]
@DanTup, changed the pool's name and ticker to CODER Coder's Cardano Stake Pool?  You probably want to re-register?

**Comment by DanTup** [comment]
@lophre yep sorry, I updated the ticket yesterday but got side-tracked with some issues and forgot to update here. I've done that now. The new ticker shows up on Adapools, pooltool, etc. now.

**Review by lophre — APPROVED** [review]

**Pull request merged**
