### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by flanpool**
{

 "ticker": "FLAN",                                                       # Mandatory
 "poolId": "pool1vcuefhjjncmsz6ww4p76f3d4hxtl3cd60tr332fwvz5essrk4n4",  # Mandatory
 "social": {                                                            # At least 1 Mandatory more optional
   "twitter": "Flantoshi",
   "facebook": "",  
   "instagram": " ",
   "youtube": " "
 },

### CODE REVIEW

**Review by Bez625 — CHANGES_REQUESTED** [review]
You need to add your entry to the `registry.json` and not the `README.md` file. Please take a look at the other pull requests if you need inspiration

**Comment by Bez625** [comment]
Please fix or I will look to close in the coming weeks

**Comment by wcatz** [comment]
You can close this. Flan retired his pool.

**Comment by Bez625** [comment]
> You can close this. Flan retired his pool.

Thanks a lot for letting me know!

**Pull request closed without merging**
