### PR TITLE
Adding BREW

### PR DESCRIPTION
**Pull request by cjkoepke**
### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [x] Added a telegram handle of an **individual** and not that of a group or channel.
- [x] Added a social media account with activity.
- [x] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [x] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [x] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

### CODE REVIEW

**Review by Bez625 — CHANGES_REQUESTED** [review]
The data looks fine, however it is mismerged with upstream and I do not have permissions to change your code. Please can you update from upstream master branch?

**Comment by cjkoepke** [comment]
> The data looks fine, however it is mismerged with upstream and I do not have permissions to change your code. Please can you update from upstream master branch?

Should be good now!

**Comment by cjkoepke** [comment]
@Bez625 just bumping this as I don't want upstream to get out of date again.

**Comment by cjkoepke** [comment]
@Bez625 Just checking in again, I'd love to announce this once merged.

**Pull request merged**
