### PR TITLE
Update registry.json

### PR DESCRIPTION
**Pull request by krypt01337**
### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [x] Added a telegram handle of an **individual** and not that of a group or channel.
- [x] Added a social media account with activity.
- [x] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [x] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [x] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

### CODE REVIEW

**Comment by krypt01337** [comment]
Adding 1337

**Comment by krypt01337** [comment]
Done. 👍--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2023-03-24, 11:53 Chris Berry ***@***.***> wrote:

   
  I've requested to follow you so i can verify your twitter :-) please accept

**Comment by Bez625** [comment]
> Done. --Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2023-03-24, 11:53 Chris Berry ***@***.***> wrote: I've requested to follow you so i can verify your twitter :-) please accept —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

I still dont have access, i requested for @HoneypotLambda

**Comment by Bez625** [comment]
Please can you address the comments or I'll close in the coming weeks

**Comment by krypt01337** [comment]
Hi. I can't see you following me on twitter. Could you try following me again?/Tobbe--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2023-04-10, 09:42 Chris Berry ***@***.***> wrote:

   
  Please can you address the comments or I'll close in the coming weeks

**Comment by Bez625** [comment]
I'm going to close this as there has been no update. If you wish to join still please raise a new PR

**Pull request closed without merging**
