### PR TITLE
Anew pool registration

### PR DESCRIPTION
**Pull request by comozo**
### Commitment

By submitting this PR I agree that I will fight for the full decentralization of Cardano by only running a single pool and reporting members that are breaking the rules by running multiple pools.

#### PR Checklist

I have:
- [x] Added a telegram handle of an **individual** and not that of a group or channel.
- [x] Added a social media account with activity.
- [x] Removed any `@` characters from Telegram, Instagram or Twitter handles.
- [x] Provided my operator name as my real full name, my real first name, or I have left that field blank.
- [x] Included all social media fields in the PR even if they are blank (this will fail validation if not done).

### CODE REVIEW

**Review by Bez625 — CHANGES_REQUESTED** [review]
This PR is fine, but it is mismerged and I do not have permission to edit. Please either allow edits by maintainers or rebase off the original repo master

**Comment by comozo** [comment]
@Bez625 Hello I have fixed the PR. Please merge when you can. Thanks

**Comment by comozo** [comment]
Hello @Bez625  I think this PR is ready to be merged. Thank you

**Comment by Bez625** [comment]
There are branch conflicts and it looks like you have disabled maintainers being able to edit your changes so I can't fix for you. Can you please fix or at least allow me to edit?

**Comment by Bez625** [comment]
Closing as no updates. Please feel free to raise a new PR if you still wish to join

**Pull request closed without merging**
