### PR TITLE
southtyrolpool

### PR DESCRIPTION
**Pull request by fisch192**

### CODE REVIEW

**Review by lophre — CHANGES_REQUESTED** [review]
You need to provide us with a real Telegram user account as it is needed to authenticate CSPA SPOs in our Telegram voting channel.

**Review by lophre — CHANGES_REQUESTED** [review]
Also, your pool id is : 2dabd15e4759334738940a65e06b6589f674a29347db0a36d75a5d36

**Comment by fisch192** [comment]
changed telegram account

**Comment by fisch192** [comment]
Hi ,

i have changed the telegram account info.



Am 24.03.2021 um 05:43 schrieb lophre ***@***.***>:

﻿

@lophre requested changes on this pull request.

Also, your pool id is : 2dabd15e4759334738940a65e06b6589f674a29347db0a36d75a5d36

**Review by lophre — APPROVED** [review]

**Pull request merged**
